/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ztbd_qf_com_jnidemox4_JniUtils */

#ifndef _Included_ztbd_qf_com_jnidemox4_JniUtils
#define _Included_ztbd_qf_com_jnidemox4_JniUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ztbd_qf_com_jnidemox4_JniUtils
 * Method:    getStr
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ztbd_qf_com_jnidemox4_JniUtils_getStr
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
